config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'orders/list'
  root 'menus#item'
  devise_for :employees
  devise_for :customers
  get 'employee/index'
  get 'customer/index'


  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'menus/new'
  get 'menus/edit'
  get 'menus/index'
  get 'menus/menu_deal'
  get 'menus/menu_item'
  resources :food_items, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'food_items/index'
  get 'food_items/new'
  get 'food_items/edit'
  resources :discounts, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'discounts/index'
  get 'discounts/new'
  get 'discounts/edit'
  resources :vouchers, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'vouchers/index'
  get 'vouchers/new'
  get 'vouchers/edit'
  resources :deals, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'deals/index'
  get 'deals/new'
  get 'deals/edit'
  resources :reviews, only: [:index]
  get 'reviews/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/add_on.rb
class AddOn < ApplicationRecord
    has_many :menu_items, through: :menu_item_addons 
    has_many :ordered_addons
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include DeviseInvitable::Inviter
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, :dependent => :destroy

  def name
    " #{first_name} #{last_name}"
  end

  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new('||',
      Arel::Nodes::InfixOperation.new('||',
        parent.table[:first_name], Arel::Nodes.build_quoted(' ')
      ),
      parent.table[:last_name]
    )
  end

end

app/models/deal.rb
class Deal < ApplicationRecord
  has_many :menu_items, as: :MenuItemable
  has_many :order_items, as: :OrderItemable
  has_many :order_histories
  has_many :deal_items, :dependent => :destroy

  def name
    "#{deal_name}"
  end
end

app/models/deal_item.rb
class DealItem < ApplicationRecord
  belongs_to :DealItemable, polymorphic: true
  belongs_to :deal
end

app/models/discount.rb
class Discount < ApplicationRecord
  enum disc_type: {
    Percent: 0,
    Flat: 1
  }

  belongs_to :restaurant
  has_many :vouchers, :dependent => :destroy
  has_many :food_items

end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :restaurant
  has_many :subordinates, class_name: "Employee",
                          foreign_key: "manager_id"

  belongs_to :manager, class_name: "Employee", optional: true
  enum position: {
    Staff: 0,
    Manager: 1
  }

  def name
    " #{first_name} #{last_name}"
  end

end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :discount
  belongs_to :group_item
  has_many :order_items, as: :OrderItemable
  has_many :deal_items, as: :DealItemable
  has_many :food_item_options
  has_many :order_histories

  def name
    "#{item_name}"
  end

  def food_discount
    discount.disc_percent
  end

  def group_name
    group_item.groupItem_name
  end
end

app/models/group_item.rb
class GroupItem < ApplicationRecord
  has_many :menu_items, as: :MenuItemable
  has_many :food_items, :dependent => :destroy
  has_many :order_histories
  has_many :deal_items, as: :DealItemable

  def name
    "#{groupItem_name}"
  end

end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  has_many :menu_timings, :dependent => :destroy
  has_many :menu_items, :dependent => :destroy
  accepts_nested_attributes_for :menu_timings, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :menu_items, allow_destroy: true, reject_if: :all_blank

  def name
    " #{menu_name} "
  end

  def rest_name
    restaurant.name
  end

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :MenuItemable, polymorphic: true
  belongs_to :menu
  has_many :add_ons, through: :menu_item_addons
  has_many :optional_items, through: :menu_optional_items

  def deal_name
    MenuItemable.deal_name
  end

  
end

app/models/menu_timing.rb
class MenuTiming < ApplicationRecord
  enum week_day: {
    Monday: 0,
    Tuesday: 1,
    Wedensday: 2,
    Thursday: 3,
    Friday: 4,
    Saturday: 5,
    Sunday: 6
  }
  belongs_to :menu

  delegate :restaurant, to: :menu

  def name
    "#{start_time} to #{end_time}"
  end

  def rest_name
    restaurant.name
  end
end

app/models/optional_item.rb
class OptionalItem < ApplicationRecord
  has_many :menu_items, through: :menu_optional_items
  has_many :food_item_options
  has_many :ordered_options
end

app/models/order.rb
class Order < ApplicationRecord
  enum order_status: {
    Draft: 0,
    Ordered: 1,
    Preparing: 2,
    Checking: 3,
    Prepared: 4,
    Delivering: 5,
    TakenOver: 6,
    Cancelled: 7
  }

  belongs_to :customer
  belongs_to :voucher
  belongs_to :payment
  validates :payment_id, uniqueness: true
  belongs_to :restaurant
  belongs_to :review
  validates :review_id, uniqueness: true
  has_many :order_items, :dependent => :destroy

  delegate :first_name, :last_name, :address, :email, :contact, to: :customer

  def name
    "#{first_name} #{last_name}"
  end

  def order_payment
    payment.total_payment
  end
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  belongs_to :deal
  belongs_to :food_item
  belongs_to :group_item
  belongs_to :order_item
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :OrderItemable, polymorphic: true
  belongs_to :order
  has_many :ordered_addons, :dependent => :destroy
  has_many :ordered_options, :dependent => :destroy
  has_many :order_histories

end

app/models/ordered_addon.rb
class OrderedAddon < ApplicationRecord
  belongs_to :add_on
  belongs_to :order_item
end

app/models/payment.rb
class Payment < ApplicationRecord
  enum payment_type: {
    Cash_on_Delivery: 0,
    Online: 1
  }
  has_one :order, :dependent => :destroy
  has_one :payment_cutoff, :dependent => :destroy

  def name
    "#{payment_type}"
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  enum status: {
    Close: 0,
    Open: 1
  }
  has_many :menus, :dependent => :destroy
  has_many :restaurant_timings, :dependent => :destroy
  has_many :employees, :dependent => :destroy
  has_many :discounts, :dependent => :destroy
  has_many :orders, :dependent => :destroy
  has_one :payment_cutoff, :dependent => :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  enum rating_desc: {
    Worst: 0,
    Poor: 1,
    Average: 2,
    Good: 3,
    Excellent: 4
  }
  has_one :order, :dependent => :destroy

  def name
    "#{rating_desc}"
  end
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  enum status: {
    Invalid: 0,
    Valid: 1
  }
  has_many :voucher_timelines, :dependent => :destroy
  accepts_nested_attributes_for :voucher_timelines, allow_destroy: true, reject_if: :all_blank
  validates_associated :voucher_timelines
  belongs_to :discount
  has_many :orders, :dependent => :destroy

  delegate :restaurant, to: :discount
  delegate :disc_percent, to: :discount
  delegate :disc_type, to: :discount

  def name
    "#{promo_code}"
  end

end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  def index
  end
end

app/views/employee/_card.html.erb
<div class="container-fluid px-4">
  <h1 class="mt-4">Welcome!</h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
  </ol>
  <div class="row">
    <div class="col-xl-3 col-md-6">
      <div class="card  text-black mb-4">
        <div class="card-body">Total Earnings</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <div class="small text-black">$24.98</div>
        </div>
      </div>
    </div>

    <div class="col-xl-3 col-md-6">
      <div class="card  text-black mb-4">
        <div class="card-body">Total Orders</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <div class="small text-black">24</div>
        </div>
      </div>
    </div>

    <div class="col-xl-3 col-md-6">
      <div class="card  text-black mb-4">
        <div class="card-body">Total Visitors</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <div class="small text-black">74.98</div>
        </div>
      </div>
    </div>

    <div class="col-xl-3 col-md-6">
      <div class="card  text-black mb-4">
        <div class="card-body">Customer Satisfaction</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <div class="small text-black">$24.98</div>
        </div>
      </div>
    </div>

    <%# <div class="col-xl-3 col-md-6">
      <div class="card bg-primary text-white mb-4">
        <div class="card-body">Total Earnings</div>
        <div class="card-footer d-flex align-items-center justify-content-between">
          <a class="small text-white stretched-link" href="#">View Details</a>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div> %>

  </div>
</div>

app/views/employee/_employee_fields.html.erb
<div><%= f.label :label_name %><br /><%= f.text_field :label_name %></div>

app/views/employee/_navigation.html.erb
<% if current_employee%>
  <div class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
      <!-- Navbar Brand-->
      <a class="navbar-brand ps-3" href="index.html">Restaurant Panel</a>

      <!-- Sidebar Toggle-->
      <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>

      <!-- Navbar Search-->
      <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
          <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
          <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
      </form>

      <!-- Navbar-->
      <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#!">Settings</a></li>
            <li><a class="dropdown-item" href="#!">Activity Log</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><%= link_to 'Logout', destroy_employee_session_path, method: :delete, class: "dropdown-item"%></li>
          </ul>
        </li>
      </ul>

    </nav>
  </div>
<% end %>

app/views/employee/_sidenav.html.erb
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
      <div class="nav">
        <div class="sb-sidenav-menu-heading">Core</div>
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseDashboard" aria-expanded="false" aria-controls="collapseDashboard">
          <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
          Dashboard
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>

        <div class="collapse" id="collapseDashboard" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to 'Analytics', employee_index_path, :class => "nav-link" %>
            <%= link_to 'Ratings', reviews_index_path, :class => "nav-link" %>
          </nav>
        </div>

        <div class="sb-sidenav-menu-heading">Interface</div>
        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
          <div class="sb-nav-link-icon"><i class="fas fa-bars"></i></div>
          Restaurant Menus
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>

        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to 'Menus', menus_index_path, :class => "nav-link" %>
            <%= link_to 'Items', food_items_index_path, :class => "nav-link" %>

            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
            Deals
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>

            <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
              <nav class="sb-sidenav-menu-nested nav">
                <%= link_to 'Add New Deal', deals_new_path, :class => "nav-link" %>
                <%= link_to 'Deal Offers', deals_index_path, :class => "nav-link" %>
              </nav>
            </div>

            <%= link_to 'Options', menus_index_path, :class => "nav-link" %>
            <%= link_to 'AddOns', menus_index_path, :class => "nav-link" %>
          </nav>
        </div>

        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseOrders" aria-expanded="false" aria-controls="collapseOrders">
          <div class="sb-nav-link-icon"><i class="fas fa-hamburger"></i></div>
          Orders
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseOrders" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to 'Order List', orders_list_path, :class => "nav-link" %>
          </nav>
        </div>


        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseDiscounts" aria-expanded="false" aria-controls="collapseDiscounts">
          <div class="sb-nav-link-icon"><i class="fas fa-tag"></i></i></div>
          Discounts
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseDiscounts" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to 'Discount',discounts_index_path, :class => "nav-link" %>
            <%= link_to 'Vouchers', vouchers_index_path, :class => "nav-link" %>
          </nav>
        </div>

        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
          <div class="sb-nav-link-icon"><i class="fa fa-user"></i></div>
          Customers
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to 'Customers', customer_index_path, :class => "nav-link" %>
          </nav>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/employee/index.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
        <div id="layoutSidenav">
          <%= render 'employee/sidenav' %>
          <div id="layoutSidenav_content">
            <main>
              <%= render 'employee/card'%>
              <div class="container-fluid px-4">


              </div>
            </main>
          </div>
        </div>
  </div>
<% end %>

app/views/employees/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/employees/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>