config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'orders/list'
  root 'menus#item'
  devise_for :employees
  devise_for :customers
  get 'employee/index'
  get 'customer/index'


  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'menus/new'
  get 'menus/edit'
  get 'menus/index'
  get 'menus/menu_deal'
  get 'menus/menu_item'
  resources :food_items, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'food_items/index'
  get 'food_items/new'
  get 'food_items/edit'
  resources :discounts, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'discounts/index'
  get 'discounts/new'
  get 'discounts/edit'
  resources :vouchers, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'vouchers/index'
  get 'vouchers/new'
  get 'vouchers/edit'
  resources :deals, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'deals/index'
  get 'deals/new'
  get 'deals/edit'
  resources :reviews, only: [:index]
  get 'reviews/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :discount
  belongs_to :group_item
  has_many :order_items, as: :OrderItemable
  has_many :deal_items, as: :DealItemable
  has_many :food_item_options
  has_many :order_histories

  def name
    "#{item_name}"
  end

  def food_discount
    discount.disc_percent
  end

  def group_name
    group_item.groupItem_name
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def index
    @rest = current_employee.restaurant
    @q = @rest.menus.ransack(params[:q])
    @pagy, @menus = pagy(@q.result(distinct: true), items: params[:per_page])
  end

  def new
    @food_item = FoodItem.new
  end

  def create
    @food_item = FoodItem.create(food_params)
    respond_to do |format|
      if @food_item.save
        format.html {redirect_to food_items_index_path, notice: "Item created Successfully"}
      else
        format.html {render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @food_item = FoodItem.find(params[:id])
  end

  def update
    @food_item = FoodItem.find(params[:id])
    respond_to do |format|
      if @food_item.update(food_params)
        format.html {redirect_to food_items_index_path, notice: "Item updated Successfully"}
      else
        format.html {render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food_item = FoodItem.find(params[:id])
    @food_item.destroy
  end

  private

  def food_params
    params.require(:food_item).permit(:item_name, :item_price, :discount_id, :group_item_id)
  end
end

app/views/food_items/_form.html.erb
<h1>Food Item </h1>
<%= form_with model: @food_item, local: true do |f| %>
  <div class="row">
    <div class="form-group col-6">
      <%= f.label :item_name %>
      <%= f.text_field :item_name, class: "form-control" %>
    </div>

    <div class="form-group col-6">
      <%= f.label :item_price %>
      <%= f.text_field :item_price, class: "form-control" %>
    </div>

  </div>

  <div class="row">
    <div class="form-group col-6">
      <%= f.label :discount %>
      <%= f.select :discount_id, current_employee.restaurant.discounts.to_a.map { |t| ["#{t.disc_percent}%  #{t.disc_type}", t.id] }, {include_blank: true}, class: "form-select" %>
    </div>

    <div class="form-group col-6">
      <%= f.label :category %>
      <%= f.select :group_item_id, GroupItem.all.to_a.map { |t| ["#{t.groupItem_name}", t.id] }, {include_blank: true}, class: "form-select" %>
    </div>

  </div>
  <br>

  <div class="form-group">
    <%= f.submit %>
    <%= link_to "cancel", :back, class: "btn-primary", class:"rightButton" %>
  </div>
<% end %>

app/views/food_items/_itemTable.html.erb
<div class="container-fluid px-4">
  <h1 class="mt-4">Food Items</h1>
  <div class="card mb-4">
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Food Items
      <%= button_to "Add New Food Item", food_items_new_path, :method => :get, class:"rightButton" %>
    </div>

    <div class="card-body">
      <table id="datatablesSimple">
        <thead>
          <tr>
            <th>Item ID</th>
            <th>Item Name</th>
            <th>Item Category</th>
            <th>Item Price</th>
            <th>Discount</th>
          </tr>
        </thead>

        <tbody>
          <% @menu.each do |menu| %>
            <% menu.menu_items.each do |menu_items| %>
              <% if menu_items.MenuItemable_type == "GroupItem" %>
                <% menu_items.MenuItemable.food_items.each do |food_items| %>
                  <tr>
                    <td class="counterCell"></td>
                    <td><%= food_items.item_name %></td>
                    <td><%= food_items.group_name %></td>
                    <td><%= food_items.item_price %></td>
                    <td><%= food_items.food_discount %>%</td>
                    <td><%= button_to "Update", edit_food_item_path(food_items) ,:method => :get %></td>
                    <td><%= button_to "Delete", food_item_path(food_items), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/food_items/_item_table.html.erb
<div class="container-fluid px-4">
  <h1 class="mt-4">Food Items</h1>
  <div class="card mb-4">
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Food Items
      <%= button_to "Add New Food Item", food_items_new_path, :method => :get, class:"rightButton" %>
    </div>

    <div class="card-body">
      <div class="row">
        <div class="col-6">
          <%= form_with url: "/food_items", method: :get do |form| %>
            entries per page
            <%= select_tag "per_page", options_for_select([5,10,20,50], :selected=>params[:per_page]),  { onchange: "this.form.submit();"} %>
          <% end %>
        </div>
      </div>
      <br/>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th> ID</th>
            <th>Item Name</th>
            <th>Item Category</th>
            <th>Item Price</th>
            <th>Discount</th>
          </tr>
        </thead>

        <tbody>
          <% @menus.each do |menu| %>
            <% menu.menu_items.each do |menu_items| %>
              <% if menu_items.MenuItemable_type == "GroupItem" %>
                <% menu_items.MenuItemable.food_items.each do |food_items| %>
                  <tr>
                    <td class="counterCell"></td>
                    <td><%= food_items.item_name %></td>
                    <td><%= food_items.group_name %></td>
                    <td><%= food_items.item_price %></td>
                    <td><%= food_items.food_discount %>%</td>
                    <td><%= button_to "Update", edit_food_item_path(food_items) ,:method => :get %></td>
                    <td><%= button_to "Delete", food_item_path(food_items), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>

      <%= pagy_bootstrap_nav(@pagy).html_safe %>
    </div>
  </div>

</div>

app/views/food_items/edit.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
    <div id="layoutSidenav">
      <%= render 'employee/sidenav' %>
      <div id="layoutSidenav_content">
        <main>
          <%= render 'employee/card' %>
          <div class="container-fluid px-4">
            <div class="container">
              <%= render 'form' %>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
<% end %>

app/views/food_items/index.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
    <div id="layoutSidenav">
      <%= render 'employee/sidenav' %>
      <div id="layoutSidenav_content">
        <main>
          <%= render 'employee/card' %>
          <div class="container-fluid px-4">
            <%= render 'item_table' %>
          </div>
        </main>
      </div>
    </div>
  </div>
<% end %>

app/views/food_items/new.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
    <div id="layoutSidenav">
      <%= render 'employee/sidenav' %>
      <div id="layoutSidenav_content">
        <main>
          <%= render 'employee/card' %>
          <div class="container-fluid px-4">
            <div class="container">
              <%= render 'form' %>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
<% end %>