config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'orders/list'
  root 'menus#item'
  devise_for :employees
  devise_for :customers
  get 'employee/index'
  get 'customer/index'


  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'menus/new'
  get 'menus/edit'
  get 'menus/index'
  get 'menus/menu_deal'
  get 'menus/menu_item'
  resources :food_items, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'food_items/index'
  get 'food_items/new'
  get 'food_items/edit'
  resources :discounts, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'discounts/index'
  get 'discounts/new'
  get 'discounts/edit'
  resources :vouchers, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'vouchers/index'
  get 'vouchers/new'
  get 'vouchers/edit'
  resources :deals, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'deals/index'
  get 'deals/new'
  get 'deals/edit'
  resources :reviews, only: [:index]
  get 'reviews/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/discount.rb
class Discount < ApplicationRecord
  enum disc_type: {
    Percent: 0,
    Flat: 1
  }

  belongs_to :restaurant
  has_many :vouchers, :dependent => :destroy
  has_many :food_items

end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  def index
    @rest = current_employee.restaurant
    @q = @rest.discounts.ransack(params[:q])
    @pagy, @discs = pagy(@q.result(distinct: true), items: params[:per_page])
  end

  def new
    @rest = current_employee.restaurant
    @disc = @rest.discounts.new
  end

  def create
    @rest = current_employee.restaurant
    @disc = @rest.discounts.new(discount_params)
    respond_to do |format|
      if @disc.save
        format.html {redirect_to discounts_index_path, notice: "Discount created Successfully"}
      else
        format.html {render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @disc = Discount.find(params[:id])
  end

  def update
    @disc = Discount.find(params[:id])
    respond_to do |format|
      if @disc.update(discount_params)
        format.html {redirect_to discounts_index_path, notice: "Discount updated Successfully"}
      else
        format.html {render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @disc = Discount.find(params[:id])
    @disc.destroy
  end

  private

  def discount_params
    params.require(:discount).permit(:disc_percent, :disc_type)
  end
end

app/views/discounts/_discountTable.html.erb
<div class="container-fluid px-4">
  <h1 class="mt-4">Restaurant Discounts</h1>
  <div class="card mb-4">
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Discounts
      <%= button_to "Add New Discount", discounts_new_path, :method => :get, class:"rightButton" %>
    </div>

    <div class="card-body">
      <table id="datatablesSimple">
        <thead>
          <tr>
            <th>ID</th>
            <th>Percentage</th>
            <th>Type</th>
            <th>Date</th>
          </tr>
        </thead>

        <tbody>
          <% @disc.each do |ds| %>
            <tr>
              <td class="counterCell"></td>
              <td><%= ds.disc_percent %>%</td>
              <td><%= ds.disc_type %></td>
              <td><%= ds.created_at %></td>
              <td><%= button_to "Update", edit_discount_path(ds), :method => :get %></td>
              <td><%= button_to "Delete", discount_path(ds), :method => :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/discounts/_discount_table.html.erb
<div class="container-fluid px-4">
  <h1 class="mt-4">Restaurant Discounts</h1>
  <div class="card mb-4">
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table me-1"></i>
      Discounts
      <%= button_to "Add New Discount", discounts_new_path, :method => :get, class:"rightButton" %>
    </div>

    <div class="card-body">
      <div class="row">
        <div class="col-6">
          <%= form_with url: "/discounts", method: :get do |form| %>
            entries per page
            <%= select_tag "per_page", options_for_select([5,10,20,50], :selected=>params[:per_page]),  { onchange: "this.form.submit();"} %>
          <% end %>
        </div>
        <div class="col-6">
          <%= render 'search_form' %>
        </div>
      </div>
      <br/>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th><%= sort_link @q, :disc_percent, "Percentage", class:"sort-header"%></th>
            <th><%= sort_link @q, :disc_type, "Type", class:"sort-header"%></th>
            <th><%= sort_link @q, :created_at, "Date", class:"sort-header"%></th>
          </tr>
        </thead>

        <tbody>
          <% @discs.each do |ds| %>
            <tr>
              <td class="counterCell"></td>
              <td><%= ds.disc_percent %>%</td>
              <td><%= ds.disc_type %></td>
              <td><%= ds.created_at %></td>
              <td><%= button_to "Update", edit_discount_path(ds), :method => :get %></td>
              <td><%= button_to "Delete", discount_path(ds), :method => :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= pagy_bootstrap_nav(@pagy).html_safe %>
    </div>

  </div>
</div>

app/views/discounts/_form.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
        <div id="layoutSidenav">
          <%= render 'employee/sidenav' %>
          <div id="layoutSidenav_content">
            <main>
              <%= render 'employee/card' %>
              <div class="container-fluid px-4">
                <div class="container">
                  <h1>Restaurant Discount </h1>
                  <%= form_with model: @disc, local: true do |f| %>
                    <div class="row">
                      <div class="form-group">
                        <%= f.label :disc_percent %>
                        <%= f.text_field :disc_percent, class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <%= f.label :disc_type %>
                          <%= f.text_field :disc_type, class: "form-control", :disabled => true %>
                          <%= f.select :disc_type, options_for_select(Discount::disc_types.map{ |value, index| "#{value}" }), {include_blank: true}, class: "form-select" %>
                      </div>
                    </div>
                    <br>
                    <div class="form-group">
                      <%= f.submit %>
                      <%= link_to "cancel", :back, class: "btn-primary", class:"rightButton" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </main>
          </div>
        </div>
  </div>
<% end %>

app/views/discounts/_search_form.html.erb
<%= search_form_for @q, url:discounts_index_url do |f| %>
  <%= f.search_field :disc_type_or_disc_percent_eq, placeholder:"Search....", class:"rightButton" %>
<% end %>

app/views/discounts/edit.html.erb
<%= render 'form' %>

app/views/discounts/index.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
    <div id="layoutSidenav">
      <%= render 'employee/sidenav' %>
      <div id="layoutSidenav_content">
        <main>
          <%= render 'employee/card' %>
          <div class="container-fluid px-4">
            <%= render 'discount_table' %>
          </div>
        </main>
      </div>
    </div>
  </div>
<% end %>

app/views/discounts/new.html.erb
<%= render 'form' %>