config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'orders/list'
  root 'menus#item'
  devise_for :employees
  devise_for :customers
  get 'employee/index'
  get 'customer/index'


  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'menus/new'
  get 'menus/edit'
  get 'menus/index'
  get 'menus/menu_deal'
  get 'menus/menu_item'
  resources :food_items, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'food_items/index'
  get 'food_items/new'
  get 'food_items/edit'
  resources :discounts, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'discounts/index'
  get 'discounts/new'
  get 'discounts/edit'
  resources :vouchers, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'vouchers/index'
  get 'vouchers/new'
  get 'vouchers/edit'
  resources :deals, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'deals/index'
  get 'deals/new'
  get 'deals/edit'
  resources :reviews, only: [:index]
  get 'reviews/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  enum status: {
    Invalid: 0,
    Valid: 1
  }
  has_many :voucher_timelines, :dependent => :destroy
  accepts_nested_attributes_for :voucher_timelines, allow_destroy: true, reject_if: :all_blank
  validates_associated :voucher_timelines
  belongs_to :discount
  has_many :orders, :dependent => :destroy

  delegate :restaurant, to: :discount
  delegate :disc_percent, to: :discount
  delegate :disc_type, to: :discount

  def name
    "#{promo_code}"
  end

end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  def index
    @q = Voucher.ransack(params[:q])
    @pagy, @vouchers = pagy(@q.result(distinct: true), items: params[:per_page])
  end

  def new
    @voucher = Voucher.new
    @voucher.voucher_timelines.new
  end

  def create
    @voucher = Voucher.new(voucher_params)
    respond_to do |format|
      if @voucher.save
        format.html {redirect_to vouchers_index_path, notice: "Voucher created Successfully"}
      else
        format.html {render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @voucher = Voucher.find(params[:id])
  end

  def update
    @voucher = Voucher.find(params[:id])
    respond_to do |format|
      if @voucher.update(voucher_params)
        format.html {redirect_to vouchers_index_path, notice: "Voucher updated Successfully"}
      else
        format.html {render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @voucher = Voucher.find(params[:id])
    @voucher.destroy
  end

  private

  def voucher_params
    params.require(:voucher).permit(:promo_code, :discount_id, :status, voucher_timelines_attributes: [:id, :start_time, :end_time])
  end

end

app/views/vouchers/_editForm.html.erb
<h1>Edit Voucher </h1>
<%= form_with model: @voucher, local: true do |f| %>
  <div class="row">
    <div class="form-group col-6">
      <%= f.label :promo_code %>
      <%= f.text_field :promo_code, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <%= f.fields_for :voucher_timelines do |v| %>
      <div class="form-group col-6">
        <%= v.label :start_time %>
        <%= v.datetime_field :start_time, class: "form-control" %>
      </div>

      <div class="form-group col-6">
        <%= v.label :end_time %>
        <%= v.datetime_field :end_time, class: "form-control" %>
      </div>

      <div class="form-group col-6">
        <%= f.label :status %>
        <%= f.text_field :status, class: "form-control", :disabled => true %>
        <%= f.select :status, options_for_select(Voucher::statuses.map{ |value, index| "#{value}" }), {include_blank: true}, class: "form-select" %>
      </div>

      <div class="form-group col-6">
        <%= f.label :discount %>
        <%= f.select :discount_id, current_employee.restaurant.discounts.to_a.map { |t| ["#{t.disc_percent}%  #{t.disc_type}", t.id] }, {include_blank: true}, class: "form-select" %>
      </div>
    <% end %>
  </div>
  <br>

  <div class="form-group">
    <%= f.submit %>
    <%= link_to "cancel", :back, class: "btn-primary", class:"rightButton" %>
  </div>
<% end %>

app/views/vouchers/_edit_form.html.erb
<h1>Edit Voucher </h1>
<%= form_with model: @voucher, local: true do |f| %>
  <div class="row">
    <div class="form-group col-6">
      <%= f.label :promo_code %>
      <%= f.text_field :promo_code, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <%= f.fields_for :voucher_timelines do |v| %>
      <div class="form-group col-6">
        <%= v.label :start_time %>
        <%= v.datetime_field :start_time, class: "form-control" %>
      </div>

      <div class="form-group col-6">
        <%= v.label :end_time %>
        <%= v.datetime_field :end_time, class: "form-control" %>
      </div>

      <div class="form-group col-6">
        <%= f.label :status %>
        <%= f.text_field :status, class: "form-control", :disabled => true %>
        <%= f.select :status, options_for_select(Voucher::statuses.map{ |value, index| "#{value}" }), {include_blank: true}, class: "form-select" %>
      </div>

      <div class="form-group col-6">
        <%= f.label :discount %>
        <%= f.select :discount_id, current_employee.restaurant.discounts.to_a.map { |t| ["#{t.disc_percent}%  #{t.disc_type}", t.id] }, {include_blank: true}, class: "form-select" %>
      </div>
    <% end %>
  </div>
  <br>

  <div class="form-group">
    <%= f.submit %>
    <%= link_to "cancel", :back, class: "btn-primary", class:"rightButton" %>
  </div>
<% end %>

app/views/vouchers/_form.html.erb
<h1>Add New Voucher </h1>
<%= form_with model: @voucher, local: true do |f| %>
  <div class="row">
    <div class="form-group col-6">
      <%= f.label :promo_code %>
      <%= f.text_field :promo_code, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <%= f.fields_for :voucher_timelines do |v| %>
      <div class="form-group col-6">
        <%= v.label :start_time %>
        <%= v.datetime_field :start_time, class: "form-control" %>
      </div>

      <div class="form-group col-6">
        <%= v.label :end_time %>
        <%= v.datetime_field :end_time, class: "form-control" %>
      </div>

      <div class="form-group col-6">
        <%= f.label :status %>
        <%= f.select :status, options_for_select(Voucher::statuses.map{ |value, index| ["#{value}"] }), {include_blank: true}, class: "form-select" %>
      </div>

      <div class="form-group col-6">
        <%= f.label :discount %>
        <%= f.select :discount_id, current_employee.restaurant.discounts.to_a.map { |t| ["#{t.disc_percent}%  #{t.disc_type}", t.id] }, {include_blank: true}, class: "form-select" %>
      </div>
    <% end %>

  </div>
  <br>

  <div class="form-group">
    <%= f.submit %>
    <%= link_to "cancel", :back, class: "btn-primary", class:"rightButton" %>
  </div>
<% end %>

app/views/vouchers/_search_form.html.erb
<%= search_form_for @q, url:vouchers_index_url, remote: false do |f| %>
  <%= f.search_field :promo_code_eq, placeholder:"Search....", class:"rightButton" %>
<% end %>

app/views/vouchers/_tableForm.html.erb
<% @voucher.each do |voucher| %>
  <% current_employee.restaurant.discounts.each do |d| %>
    <% if d.id == voucher.discount_id %>
      <tr>
        <td class="counterCell"></td>
        <td><%= voucher.promo_code %></td>
        <td><%= voucher.status %></td>
        <td>
          <% voucher.voucher_timelines.each do |vt| %>
            <%= vt.start_time %>,
          <% end %>
        </td>

        <td>
          <% voucher.voucher_timelines.each do |vt| %>
            <%= vt.end_time %>,
          <% end %>
        </td>

        <td><%= voucher.disc_percent%>%</td>
        <td><%= voucher.disc_type%></td>
        <td><%= button_to "Update", edit_voucher_path(voucher), :method => :get %></td>
      </tr>
    <% end %>
  <% end %>
<% end %>

app/views/vouchers/_table_form.html.erb
<% @vouchers.each do |voucher| %>
  <% current_employee.restaurant.discounts.each do |d| %>
    <% if d.id == voucher.discount_id %>
      <tr>
        <td class="counterCell"></td>
        <td><%= voucher.promo_code %></td>
        <td><%= voucher.status %></td>
        <td>
          <% voucher.voucher_timelines.each do |vt| %>
            <%= vt.start_time %>,
          <% end %>
        </td>

        <td>
          <% voucher.voucher_timelines.each do |vt| %>
            <%= vt.end_time %>,
          <% end %>
        </td>

        <td><%= voucher.disc_percent%>%</td>
        <td><%= voucher.disc_type%></td>
        <td><%= button_to "Update", edit_voucher_path(voucher), :method => :get %></td>
      </tr>
    <% end %>
  <% end %>
<% end %>

app/views/vouchers/_voucher_table.html.erb
<div class="container-fluid px-4">
  <h1 class="mt-4">Restaurant Vouchers</h1>
    <div class="card mb-4">
    </div>

    <div class="card mb-4">
      <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Vouchers
        <%= button_to "Add New Voucher", vouchers_new_path, :method => :get, class:"rightButton" %>
      </div>

      <div class="card-body">
        <div class="row">
          <div class="col-6">
            <%= form_with url: "/vouchers", method: :get do |form| %>
              entries per page
              <%= select_tag "per_page", options_for_select([5,10,20,50], :selected=>params[:per_page]),  { onchange: "this.form.submit();"} %>
            <% end %>
          </div>
          <div class="col-6">
            <%= render 'search_form' %>
          </div>
        </div>
        <br/>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th><%= sort_link @q, :promo_code, "Promo Code", class:"sort-header"%></th>
              <th><%= sort_link @q, :status, "Status", class:"sort-header"%></th>
              <th><%= sort_link @q, :voucher_timeline_start_time, "Start Date", class:"sort-header"%></th>
              <th><%= sort_link @q, :voucher_timeline_end_time, "End Date", class:"sort-header"%></th>
              <th><%= sort_link @q, :disc_percent, "Discount", class:"sort-header"%></th>
              <th><%= sort_link @q, :disc_type, "Discount Type", class:"sort-header"%></th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <%= render 'table_form' %>
          </tbody>

        </table>

        <%= pagy_bootstrap_nav(@pagy).html_safe %>
      </div>

    </div>

</div>

app/views/vouchers/edit.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
    <div id="layoutSidenav">
      <%= render 'employee/sidenav' %>
      <div id="layoutSidenav_content">
        <main>
          <%= render 'employee/card' %>
          <div class="container-fluid px-4">
            <div class="container">
              <%= render 'edit_form' %>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
<% end %>

app/views/vouchers/index.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
        <div id="layoutSidenav">
          <%= render 'employee/sidenav' %>
          <div id="layoutSidenav_content">
            <main>
              <%= render 'employee/card' %>
              <div class="container-fluid px-4">
                <%= render 'voucher_table' %>

              </div>
            </main>
          </div>
        </div>
  </div>
<% end %>

app/views/vouchers/new.html.erb
<% if current_employee%>
  <%= render 'employee/navigation' %>
  <div class="sb-nav-fixed">
        <div id="layoutSidenav">
          <%= render 'employee/sidenav' %>
          <div id="layoutSidenav_content">
            <main>
              <%= render 'employee/card' %>
              <div class="container-fluid px-4">
                <div class="container">
                  <%= render 'form' %>
                </div>
              </div>
            </main>
          </div>
        </div>
  </div>
<% end %>